# Generated by Django 5.0.1 on 2025-01-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0004_news_newsimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="newsImage",
            field=models.ImageField(upload_to="news_images/"),
        ),
    ]
